import { useEffect, useRef, useState } from 'react';
import { Check, Crop, Image as ImageIcon, Minus, Plus, RotateCcw, RotateCw, X } from 'lucide-react';
import { api } from '../api/client';

type ImageKey = 'loading_image_url' | 'home_hero_image_url' | 'cart_empty_image_url' | 'orders_empty_image_url' | 'debt_image_url' | 'support_avatar_image_url' | 'lists_page_image_url' | 'requests_page_image_url';
type FitMode = 'contain' | 'cover';
type AspectPreset = '1:1' | '4:3' | '16:9' | '3:2' | '9:16' | 'custom';
type ImageStyle = { fit: FitMode; zoom: number; x: number; y: number; rotation: number; aspect: AspectPreset; aspectRatio: number };
type ShopImages = Record<ImageKey, string | null | undefined>;
type ShopSettings = ShopImages & { shop_name?: string; logo_url?: string | null; is_open?: boolean; reopening_time?: string | null; home_delivery_enabled?: boolean; announcements?: string | null; image_styles?: Record<string, Partial<ImageStyle>> | null };

const IMAGE_SLOTS: { key: ImageKey; label: string; hint: string; aspect: AspectPreset; ratio?: number; fit?: FitMode }[] = [
  { key: 'loading_image_url', label: 'Loading screen image', hint: 'Full-screen 9:16 splash — ONLY this image shows while the app loads.', aspect: '9:16', fit: 'cover' },
  { key: 'home_hero_image_url', label: 'Home hero banner', hint: 'Fills the entire customer banner — edited against the full frame.', aspect: 'custom', ratio: 1100 / 460, fit: 'cover' },
  { key: 'cart_empty_image_url', label: 'Cart — empty state', hint: 'Image shown when the customer cart has no items.', aspect: '4:3' },
  { key: 'orders_empty_image_url', label: 'Orders — empty state', hint: 'Image shown when there are no past orders.', aspect: '4:3' },
  { key: 'debt_image_url', label: 'Outstanding debt image', hint: '4:3 banner in the Account → Outstanding Debt area.', aspect: '4:3', fit: 'cover' },
  { key: 'support_avatar_image_url', label: 'Customer support image', hint: '4:3 banner at the top of the Customer Support section.', aspect: '4:3', fit: 'cover' },
  { key: 'lists_page_image_url', label: 'My Lists — page image', hint: '4:3 placeholder shown on the customer “My Lists” page.', aspect: '4:3' },
  { key: 'requests_page_image_url', label: 'Requests — page image', hint: '4:3 placeholder shown on the customer “Request an item” page.', aspect: '4:3' },
];
const ASPECTS: Record<AspectPreset, number> = { '1:1': 1, '4:3': 4 / 3, '16:9': 16 / 9, '3:2': 3 / 2, '9:16': 9 / 16, custom: 1 };
const defaultStyle = (aspect: AspectPreset = '1:1', ratio?: number, fit?: FitMode): ImageStyle => ({ fit: fit || 'contain', zoom: 1, x: 0, y: 0, rotation: 0, aspect, aspectRatio: ratio && ratio > 0 ? ratio : ASPECTS[aspect] });
const normalizeStyle = (style: Partial<ImageStyle> | undefined, aspect: AspectPreset, ratio?: number, fit?: FitMode): ImageStyle => {
  const next = { ...defaultStyle(aspect, ratio, fit), ...(style || {}) };
  return { fit: next.fit === 'cover' ? 'cover' : 'contain', zoom: Math.min(3, Math.max(1, Number(next.zoom) || 1)), x: Math.min(100, Math.max(-100, Number(next.x) || 0)), y: Math.min(100, Math.max(-100, Number(next.y) || 0)), rotation: Number(next.rotation) || 0, aspect: next.aspect || aspect, aspectRatio: Number(next.aspectRatio) > 0 ? Number(next.aspectRatio) : ratio && ratio > 0 ? ratio : ASPECTS[next.aspect || aspect] };
};

function Editor({ url, initial, onCancel, onApply }: { url: string; initial: ImageStyle; onCancel: () => void; onApply: (style: ImageStyle) => void }) {
  const [draft, setDraft] = useState(initial);
  const [dragging, setDragging] = useState(false);
  const dragStart = useRef({ x: 0, y: 0, imageX: 0, imageY: 0 });
  const frameRef = useRef<HTMLDivElement>(null);
  const update = (patch: Partial<ImageStyle>) => setDraft((current) => ({ ...current, ...patch }));
  const chooseAspect = (aspect: AspectPreset) => update({ aspect, aspectRatio: aspect === 'custom' ? draft.aspectRatio : ASPECTS[aspect] });
  const reset = () => setDraft(defaultStyle(draft.aspect, draft.aspectRatio, draft.fit));
  const beginDrag = (event: React.PointerEvent<HTMLDivElement>) => { event.currentTarget.setPointerCapture(event.pointerId); dragStart.current = { x: event.clientX, y: event.clientY, imageX: draft.x, imageY: draft.y }; setDragging(true); };
  const moveDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (!dragging || !frameRef.current) return; const bounds = frameRef.current.getBoundingClientRect(); update({ x: Math.max(-100, Math.min(100, dragStart.current.imageX + ((event.clientX - dragStart.current.x) / bounds.width) * 200)), y: Math.max(-100, Math.min(100, dragStart.current.imageY + ((event.clientY - dragStart.current.y) / bounds.height) * 200)) }); };

  return <div className="image-editor-backdrop" role="dialog" aria-modal="true" aria-label="Adjust image"><section className="image-editor">
    <header className="image-editor-head"><div><span className="eyebrow">IMAGE ADJUSTMENT</span><h2>Position this image</h2></div><button className="icon-button" onClick={onCancel} aria-label="Close editor"><X size={18} /></button></header>
    <div className="image-editor-body"><div className="editor-preview-column"><div className="image-editor-frame" ref={frameRef} style={{ aspectRatio: draft.aspectRatio }} onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={() => setDragging(false)} onPointerCancel={() => setDragging(false)}><img src={url} alt="Preview" draggable={false} style={{ objectFit: draft.fit, objectPosition: `${50 + draft.x / 2}% ${50 + draft.y / 2}%`, transform: `translate(${draft.x / 2}%, ${draft.y / 2}%) scale(${draft.zoom}) rotate(${draft.rotation}deg)` }} /><span className="editor-drag-hint"><Crop size={14} /> Drag to reposition</span></div><small className="editor-preview-note">The framed area is exactly what customers will see.</small></div>
      <div className="image-editor-controls"><div className="editor-control-group"><label>Aspect ratio</label><div className="segmented-control">{(['1:1', '4:3', '16:9', '3:2', '9:16', 'custom'] as AspectPreset[]).map((aspect) => <button type="button" key={aspect} className={draft.aspect === aspect ? 'active' : ''} onClick={() => chooseAspect(aspect)}>{aspect === 'custom' ? 'Custom' : aspect}</button>)}</div></div>
        {draft.aspect === 'custom' && <label className="custom-ratio">Custom ratio<input type="number" min="0.2" max="5" step="0.01" value={draft.aspectRatio} onChange={(event) => update({ aspectRatio: Math.max(.2, Math.min(5, Number(event.target.value) || 1)) })} /></label>}
        <div className="editor-control-group"><label>Display</label><div className="fit-buttons"><button type="button" className={draft.fit === 'contain' ? 'active' : ''} onClick={() => update({ fit: 'contain' })}>FIT</button><button type="button" className={draft.fit === 'cover' ? 'active' : ''} onClick={() => update({ fit: 'cover' })}>FILL / COVER</button></div></div>
        <div className="editor-control-group"><label htmlFor="image-zoom">Zoom <b>{Math.round(draft.zoom * 100)}%</b></label><div className="zoom-row"><Minus size={15} /><input id="image-zoom" type="range" min="1" max="3" step="0.01" value={draft.zoom} onChange={(event) => update({ zoom: Number(event.target.value) })} /><Plus size={15} /></div></div>
        <div className="rotation-buttons"><button type="button" onClick={() => update({ rotation: draft.rotation - 90 })}><RotateCcw size={15} /> Rotate left</button><button type="button" onClick={() => update({ rotation: draft.rotation + 90 })}><RotateCw size={15} /> Rotate right</button></div><button type="button" className="reset-adjustments" onClick={reset}><RotateCcw size={15} /> Reset adjustments</button>
      </div></div><footer className="image-editor-foot"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button type="button" className="primary-button" onClick={() => onApply(draft)}><Check size={16} /> Apply / Save</button></footer>
  </section></div>;
}

export default function SiteImages() {
  const [settings, setSettings] = useState<ShopSettings | null>(null); const [form, setForm] = useState<ShopImages>({} as ShopImages); const [styles, setStyles] = useState<Record<string, ImageStyle>>({}); const [editing, setEditing] = useState<{ key: ImageKey; url: string; previousUrl?: string } | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  useEffect(() => { api('/shop').then((data: ShopSettings) => { setSettings(data); setForm(Object.fromEntries(IMAGE_SLOTS.map(({ key }) => [key, data[key] || ''])) as ShopImages); setStyles(Object.fromEntries(IMAGE_SLOTS.map(({ key, aspect, ratio, fit }) => [key, normalizeStyle(data.image_styles?.[key], aspect, ratio, fit)]))); }).catch((e: any) => setError(e?.message || 'Could not load shop settings.')).finally(() => setLoading(false)); }, []);
  const uploadFile = async (key: ImageKey, file: File) => { setError(''); const fd = new FormData(); fd.append('file', file); const token = sessionStorage.getItem('admin_token'); try { const response = await fetch('http://localhost:8000/api/shop/upload-image', { method: 'POST', headers: token ? { Authorization: `Bearer ${token}` } : undefined, body: fd }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'Upload failed. Please try again.'); const url = data.url as string; const previousUrl = form[key] as string | undefined; setForm((current) => ({ ...current, [key]: url })); setEditing({ key, url, previousUrl }); setSaved(false); } catch (e: any) { setError(e?.message || 'Upload failed. Please try again.'); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!settings) return; setSaving(true); setError(''); try { const updated = await api('/shop', { method: 'PUT', body: JSON.stringify({ ...settings, ...form, image_styles: styles }) }); setSettings(updated); setSaved(true); window.setTimeout(() => setSaved(false), 2200); } catch (e: any) { setError(e?.message || 'Could not save changes.'); } finally { setSaving(false); } };
  if (loading) return <div style={{ padding: 24 }}>Loading site images...</div>;
  return <div className="site-images-page"><div className="site-images-intro"><div><span className="eyebrow">VISUAL CONTENT</span><h1>Site images</h1><p>Upload an image, then choose exactly how it is framed for customers. The original file stays unchanged.</p></div><ImageIcon size={28} /></div>{error && <div className="image-error">{error}</div>}<form onSubmit={save}><div className="site-image-list">{IMAGE_SLOTS.map(({ key, label, hint, aspect }) => { const url = form[key] as string; const style = styles[key] || defaultStyle(aspect); return <article className="site-image-row" key={key}><div className="site-image-thumb" style={{ aspectRatio: style.aspectRatio }}>{url ? <img src={url} alt="" style={{ objectFit: style.fit, objectPosition: `${50 + style.x / 2}% ${50 + style.y / 2}%`, transform: `translate(${style.x / 2}%, ${style.y / 2}%) scale(${style.zoom}) rotate(${style.rotation}deg)` }} /> : <span>none</span>}</div><div className="site-image-fields"><div><h2>{label}</h2><p>{hint}</p></div><div className="site-image-url"><input type="url" placeholder="https://... or upload below" value={url || ''} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />{url && <button type="button" className="text-danger" onClick={() => setForm({ ...form, [key]: '' })}>Remove</button>}</div><div className="site-image-actions"><label className="upload-button">Choose image<input type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) uploadFile(key, file); event.target.value = ''; }} /></label>{url && <button type="button" className="secondary-button" onClick={() => setEditing({ key, url })}>Adjust image</button>}</div></div></article>; })}</div><button className="primary-button site-images-save" type="submit" disabled={saving}>{saving ? 'Saving...' : saved ? 'Saved' : 'Save changes'}</button></form>{editing && <Editor url={editing.url} initial={styles[editing.key] || (() => { const slot = IMAGE_SLOTS.find((s) => s.key === editing.key); return defaultStyle(slot?.aspect, slot?.ratio, slot?.fit); })()} onCancel={() => { if (editing.previousUrl !== undefined) setForm((current) => ({ ...current, [editing.key]: editing.previousUrl })); setEditing(null); }} onApply={(style) => { setStyles({ ...styles, [editing.key]: style }); setEditing(null); }} />}</div>;
}